public class SalesforceDeveloper {
    public void myFirstCode() {
        string favCity= 'Bursa';
        string favMovie= 'Film';
        string favMevsim= 'Ilkbahar';

        system.debug(favCity);
        system.debug(favMovie);
        system.debug(favMevsim);


    }

    public void myFavorites() {
        String myCity= 'Houston';
        Integer myNumber= 7;

        system.debug(myCity);
        system.debug(myNumber);

        



    }



}