decimal addition=Calculator.dynamicCalculationMethod(30, 10, 'addition');
system.debug(addition);

decimal subtraction=Calculator.dynamicCalculationMethod(30, 10, 'subtraction');
system.debug(subtraction);


decimal multiplication=Calculator.dynamicCalculationMethod(30, 10, 'multiplication');
system.debug(multiplication);

decimal division=Calculator.dynamicCalculationMethod(30, 10, 'division');
system.debug(division);


